<?php
require '/home/spark2015admin/public_html/researchdb/kint/Kint.class.php';


/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function sparkswag_help($path, $arg) {
  switch ($path) {
    case "admin/help#sparkswag":
      return '<p>' . t("This is some help text in the admin menu.") . '</p>';
      break;
  }
} 

function sparkswag_menu() {
  $items = array();
  

$items['sparkswag/form1'] = array( //this creates a URL that will call this form at "sparkswag/form1"
    'title' => 'My First Form', //page title
    'description' => 'A form to fill out info',
    'page callback' => 'drupal_get_form', //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('sparkswag_myform1_form'), //put the name of the form here
    'access callback' => TRUE
  );
  return 

$items;
}

/**
 * Implements hook_block_info().
 */
function sparkswag_block_info() {
  $blocks['myblock1'] = array(
    // The name that will appear in the block list.
    'info' => t('Sparkswag block'),
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
  );
  
 
  
  return $blocks;
}

function sparkswag_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'myblock1':
		return $block;
        $node = menu_get_object();//What does this do???
        $block['subject'] = t('This is a subject for block.');
        $form = drupal_get_form('sparkswag_myform1_form');	//call form
        $block['content'] = drupal_render($form);	//get html from $form put in block content.
        break;
  return $block;
  }
}


function sparkswag_myform1_form($form, &$form_state){
//d($form);

$form['name'] = array(
    '#type' => 'textfield',
	'#name' => 'name',
	'#maxlength'=> 255,
	'#size'=> 30,
    '#value' => t('Name'),
  );

$form['description'] = array(
    '#type' => 'textarea',
	'#name' => 'description',
	'#maxlength'=> 1000,
	'#size'=> 30,
    '#value' => t('description')
  );

	$form['positions'] = array(
    '#type' => 'textfield',
	'#name' => 'positions',
	'#maxlength'=> 5,
	'#size'=> 10,
    '#value' => t('Positios available')
  );
  
  $form['startdate'] = array(
    '#type' => 'textfield',
	'#name' => 'startdate',
	'#maxlength'=> 20,
	'#size'=> 10,
    '#value' => t('Start Date')
  );
  
    $form['enddate'] = array(
    '#type' => 'textfield',
	'#name' => 'enddate',
	'#maxlength'=> 20,
	'#size'=> 10,
    '#value' => t('End Date')
  );
  
     $form['deadline'] = array(
    '#type' => 'textfield',
	'#name' => 'deadline',
	'#maxlength'=> 20,
	'#size'=> 10,
    '#value' => t('Application Deadline')
  );
  
    
    $form['location'] = array(
    '#type' => 'textfield',
	'#name' => 'location',
	'#maxlength'=> 100,
	'#size'=> 10,
    '#value' => t('Location')
  );
  
  
    $form['institution'] = array(
    '#type' => 'textfield',
	'#name' => 'institution',
	'#maxlength'=> 30,
	'#size'=> 10,
    '#value' => t('Institution')
  );
  
    $form['institutiontype'] = array(
    '#type' => 'textfield',
	'#name' => 'institutiontype',
	'#maxlength'=> 30,
	'#size'=> 10,
    '#value' => t('Institution Type')
  );
  
    $form['discipline'] = array(
    '#type' => 'textfield',
	'#name' => 'discipline',
	'#maxlength'=> 30,
	'#size'=> 10,
    '#value' => t('Discipline')
  );
  
    $form['logo'] = array(
    '#type' => 'textfield',
	'#name' => 'logo',
	'#maxlength'=> 30,
	'#size'=> 10,
    '#value' => t('Logo')
  );
  
    $form['homepage'] = array(
    '#type' => 'textfield',
	'#name' => 'homepage',
	'#maxlength'=> 100,
	'#size'=> 10,
    '#value' => t('Opportunity Homepage')
  );
  
  
    $form['gpareq'] = array(
    '#type' => 'textfield',
	'#name' => 'gpareq',
	'#maxlength'=> 5,
	'#size'=> 10,
    '#value' => t('GPA Requirement')
  );
  
  
    $form['gradereg'] = array(
    '#type' => 'textfield',
	'#name' => 'gradereg',
	'#maxlength'=> 20,
	'#size'=> 10,
    '#value' => t('Grade Level Requirement')
  );
  
    $form['paid'] = array(
    '#type' => 'checkbox',
	'#name' => 'paid'
    
  );
  
  $form['contactinfo'] = array(
    '#type' => 'textarea',
	'#name' => 'contactinfo',
	'#maxlength'=> 100,
	'#size'=> 30,
    '#value' => t('Contact Information')
  );


$form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Create!'),
  );
  d($form);
  return $form;
}

function sparkswag_myform1_form_submit($form,&$form_state){

}


